export{default as Contact} from './contact/Contact.jsx'
export{default as Intro} from './intro/Intro.jsx'
export{default as Portfolio} from './portfolio/Portfolio'
export{default as Testimonials} from './testimonials/Testimonials.jsx'
export{default as TopBar} from './topbar/Topbar.jsx'
export{default as Work} from './work/Work.jsx'